In [31]:
import numpy as np

### Задание 1

Заполните матрицу $a\left(5,\ 10\right)$ случайными целыми числами $\in \left[-10;\ 10\right]$. Выведите значения ее элементов на экран. 
1. Найдите произведение минимального элемента матрицы на сумму ее четных элементов. Выведите результат.
2. Найдите столбец матрицы с минимальной суммой положительных элементов и выведите индекс этого столбца.

In [32]:
a = np.random.randint(-10, 11, (5, 10))
a

array([[  7,   5,  -6,  -5,  -2,  -6,  -9,   6, -10,   8],
       [  8,  -6,   9,  -6,  -8,   0,  -2,   6,   3,   8],
       [  3, -10,   7,   3,   2,   4,   5,   6,  -9,   6],
       [  6,   3,  -1,  10, -10,   2,   3,  10,   5,  -4],
       [ -6,   0,  -8,   3,   6,  -9, -10,   3,  -6,   4]])

In [33]:
# 1 Найдите произведение минимального элемента матрицы на сумму ее четных элементов:

min_a = a.min()
sum_of_even = a.sum(where = a % 2 == 0)
prod = min_a * sum_of_even
print(
    (
        f'Минимальный элемент: {min_a}\n'
        f'Сумма четных элементов: {sum_of_even}\n'
        f'Произведение: {prod}'
    )
)

Минимальный элемент: -10
Сумма четных элементов: -8
Произведение: 80


In [34]:
# 2 Найдите столбец матрицы с минимальной суммой положительных элементов и выведите индекс этого столбца:

sum_of_cols = a.sum(axis=0, where = a > 0)
icol = np.argmin(sum_of_cols)
print(f'Столбец номер {icol} имеет минимальную сумму положительный элементов = {sum_of_cols[icol]}')

Столбец номер 5 имеет минимальную сумму положительный элементов = 6


### Задание 2

По имеющимся исходным данным, используя массивы NumPy, определите:

1. Состав потока в мольных долях:

$$
    \chi _i = \dfrac{\dfrac{\omega _i}{M_i}}{\sum \limits_{i=1}^{n}\dfrac{\omega _i}{M_i}}
$$

где $\chi _i$ - мольная доля $i$-го компонента; $\omega _i$ - массовая доля $i$-го компонента; $M_i$ - молярная масса $i$-го компонента; $n$ - число компонентов в системе; $i$ - индекс компонента в системе.

2. Плотность потока:

$$
    \rho = \dfrac{1}{\sum \limits_{i=1}^{n}\dfrac{\omega_i}{\rho_i}}
$$

где $\rho$ - плотность потока; $\omega _i$ - массовая доля $i$-го компонента; $\rho _i$ - плотность $i$-го компонента; $n$ - число компонентов в системе; $i$ - индекс компонента в системе.

3. Среднюю молекулярную массу потока:

$$
    m = \dfrac{1}{\sum \limits_{i=1}^{n}\dfrac{\omega_i}{M_i}}
$$

где $m$ - средняя молекулярная масса потока; $\omega _i$ - массовая доля $i$-го компонента; $M_i$ - молярная масса $i$-го компонента; $n$ - число компонентов в системе; $i$ - индекс компонента в системе.

##### Исходные данные

|Параметр|$C_1$|$C_2$|$C_3$|$iC_4$|$nC_4$|$iC_5$|$nC_5$|$nC_6$|
|:-|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
|$\omega _i$|0.1|0.1|0.1|0.4|0.2|0.05|0.03|0.02|
|$\rho _i$, г/см$^3$|0.416 |0.546|0.585|0.5510|0.6|0.616|0.6262|0.6594|
|$M _i$, г/моль|16 |30|44|58|58|72|72|86|

> Вычисления необходимо реализовать в **виде функций**.

In [35]:
def mass_to_mole_fractions(
        mf: np.ndarray,
        mr: np.ndarray
) -> np.ndarray:
    mf_by_mr = mf / mr
    s = mf_by_mr.sum()
    return mf_by_mr / s

def get_flow_property(
        mf: np.ndarray,
        prop: np.ndarray
) -> float:
    return (mf / prop).sum() ** -1

In [36]:
mf = np.array(
    [.1, .1, .1, .4, .2, .05, .03, .02]
)
rho = np.array(
    [.416, .546, .585, .551, .6, .616, .6262, .6594]
)
mr = np.array(
    [16, 30, 44, 58, 58, 72, 72, 86]
)

In [37]:
mole_fractions = mass_to_mole_fractions(mf, mr)
mole_fractions, mole_fractions.sum()

(array([0.26545413, 0.14157554, 0.09652877, 0.2929149 , 0.14645745,
        0.0294949 , 0.01769694, 0.00987736]),
 1.0)

In [38]:
flow_den = get_flow_property(mf, rho)
flow_den

0.5515207014243224

In [39]:
flow_mol_mass = get_flow_property(mf, mr)
flow_mol_mass

42.47266071679689

### Задание 3

Дана температурная зависимость кинематической вязкости воды:

|$\mathrm{T \space\left[°C\right]}$|$0$|$21.1$|$37.8$|$54.4$|$71.1$|$87.8$|$100$|
|-|-|-|-|-|-|-|-|
|$\mu_k$ $\left[10^{-3}\mathrm{м^2/с}\right]$|$1.79$|$1.13$|$0.696$|$0.519$|$0.338$|$0.321$|$0.296$|

1. Используя метод `fit()` класса `numpy.polynomial.Polynomial` подберите степень полинома (ограничим поиск в пределах $1\text{-}4$). В качестве критерия используйте среднеквадратичную ошибку:
	$$
			MSE = \dfrac{1}{n} \times \sum \limits _{i=1} ^{n} \left(y_i - \tilde{y}_i\right)^2
	$$
	где $\mathrm{MSE}$ - среднеквадратичная ошибка; $n$ - количество наблюдений; $y_i$ - фактическое значение; $\tilde{y}_i$ - предсказанное значение.
2. Используя полином с выбранной в пункте 1 степенью, определите значения $\mu_k$ при $T = 10°, \space 30°, \space  60° \text{ и } 90° \mathrm{C}$.


In [40]:
def mse(
        y: np.ndarray,
        y_calc: np.ndarray
) -> float:
    n = y.size
    return ((y - y_calc) ** 2).sum() / n

In [41]:
poly = np.polynomial.Polynomial

In [42]:
t = np.array([0, 21.1, 37.8, 54.4, 71.1, 87.8, 100])
mu = np.array([1.79, 1.13, .696, .519, .338, .321, .296])

In [43]:
poly_list = [poly.fit(x=t, y=mu, deg=i) for i in range(1, 5)]

In [44]:
for i in range(1, 5):
    err = mse(
        y=mu,
        y_calc=poly_list[i-1](t)
    )
    print(f'MSE for poly with deg {i} is {err:6.4f}')

MSE for poly with deg 1 is 0.0395
MSE for poly with deg 2 is 0.0010
MSE for poly with deg 3 is 0.0005
MSE for poly with deg 4 is 0.0004


In [45]:
t_aarray = np.array([10, 30, 60, 90])
mu_array = poly_list[-1](t_aarray)
mu_array

array([1.44845402, 0.89193745, 0.42910472, 0.31214588])

### Задание 4

Уравнение Ван-дер-Ваальса, описывающее состояние газа, можно записать в виде следующей формулы как зависимость давления $p$ газа от его молярного объема $V$ и температуры $T$:

$$
    p = \dfrac{RT}{V-b} - \dfrac{a}{V^2}
$$

где $a$ и $b$ – специальные молекулярные константы, а $R = 8.314$ $\mathrm{Дж / \left(моль \cdot K\right)}$ – универсальная газовая постоянная. 

Формулу легко преобразовать для вычисления температуры по заданному давлению и объему, но ее форма, представляющая молярный объем в  отношении к  давлению и температуре, является кубическим уравнением:

$$
    pV^3 - \left(pb + RT\right)V^2 + aV - ab = 0
$$

Все три корня этого уравнения ниже критической точки ($T_c$, $p_c$) являются действительными: наибольший и наименьший соответствуют молярному объему
газообразной фазы и жидкой фазы соответственно. Выше критической точки,
где не существует жидкая фаза, только один корень является действительным
и  соответствует молярному объему газа (в этой области его также называют
сверхкритической жидкостью, или сверхкритической средой). 

Критическая точка определяется по условию $\left(\partial p/\partial V\right)_T = \left(\partial ^2 p/\partial V^2\right)_T = 0$ и для идеального газа Ван-дер-Ваальса выводятся формулы:

$$
    T_c = \dfrac{8a}{27Rb} \qquad p_c = \dfrac{a}{27b^2}
$$

Для этана $\left(C_2H_6\right)$ константы Ван-дер-Ваальса $a  = 0.5580$ $л^2 \cdot Па \cdot м^6 \cdot моль^{-2}$ и $b = 65.1 \times 10^{-6} \space м^3 \cdot моль^{-1}$.

- Реализовать функцию для нахождения критической точки газа по уравнению Ван-дер-Ваальса.
- Реализовать функцию для нахождения молярного объема газа с учетом критической точки. Определить молярный объем при комнатной температуре и давлении ($298$ $\mathrm{К}$, $101325$ $\mathrm{Па}$) и при следующих условиях: температура $500$ $\mathrm{К}$, давление $12\times 10^6$ $\mathrm{Па}$.

In [46]:
poly = np.polynomial.Polynomial

In [47]:
def calculate_critical_point(
        a: float,
        b: float,
        r: float = 8.314
) -> tuple[float, float]:
    tc: float = 8 * a / (27 * r * b)
    pc: float = a / (27 * b ** 2)
    return tc, pc

In [48]:
def calculate_gas_molar_volume(
        t: float,
        p: float,
        a: float,
        b: float,
        r: float = 8.314
) -> float:
    tc, pc = calculate_critical_point(a, b)
    pol = poly(
        [
            -a * b, 
            a, 
            -(p * b + r * t), 
            p
        ]
    )
    roots = pol.roots()
    roots = roots[np.isreal(roots)].real

    if t > tc and p > pc:
        root, = roots
        return root
    
    return roots.max()

In [49]:
a, b = .558, 65.1e-6

In [50]:
tc, pc = calculate_critical_point(a, b)
print(f'Критическая точка этана: tc = {tc:8.4f} [K], pc = {pc:8.4g} [Pa]')

Критическая точка этана: tc = 305.4706 [K], pc = 4.877e+06 [Pa]


In [51]:
t, p = 298, 101325
vm = calculate_gas_molar_volume(t, p, a, b)
print(f'Молярный объем этана при {t} [K] и {p} [Па] равен {vm:6.4f} м^3')

Молярный объем этана при 298 [K] и 101325 [Па] равен 0.0243 м^3


In [52]:
t, p = 500, 12e6
vm = calculate_gas_molar_volume(t, p, a, b)
print(f'Молярный объем этана при {t} [K] и {p} [Па] равен {vm:6.4f} м^3')

Молярный объем этана при 500 [K] и 12000000.0 [Па] равен 0.0003 м^3


### Задание  5

Двухпараметрическое уравнение состояния Редлиха-Квонга имеет следующий вид:

$$
	P = \dfrac{RT}{V-b} - \dfrac{a}{T^{0.5}V\left(V+b\right)}
$$

где $P$ - давление, $\mathrm{Па}$; $T$ - абсолютная температура, $\mathrm{K}$; $V$ - мольный объем, $\mathrm{м^3/моль}$; $R = 8.314$ - универсальная газовая постоянная, $\mathrm{Дж/\left(моль \cdot К\right)}$.

Константы $a$ и $b$ зависят от конкретного вещества и вычисляются по следующим формулам:

$$
	a = \dfrac{1}{9 \cdot \left(\sqrt[3]{2}-1\right)} \dfrac{R^2T_c^{2.5}}{P_c}
$$

$$
	b = \dfrac{\sqrt[3]{2}-1}{3}\dfrac{RT_c}{P_c}
$$

где $T_c$ - критическая температура, $\mathrm{К}$; $P_c$ - критическое давление, $\mathrm{Па}$.

Уравнение состояния Редлиха-Квонга можно записать относительно коэффициента сжимаемости $Z$:

$$
	Z^3 - Z^2 + \left(A - B^2 - B\right)Z - AB = 0
$$

где $A = \dfrac{aP}{R^2T^{2.5}}$; $B=\dfrac{bP}{RT}$.

С учетом того, что коэффициент сжимаемости $Z = \dfrac{PV}{RT}$ плотность газа может быть выражена следующим образом:

$$
	\rho = \dfrac{M \cdot P}{R \cdot T \cdot Z}
$$

где $\rho$ - плотность газа, $\mathrm{кг/м^3}$; $M$ - молярная масса газа, $\mathrm{кг/моль}$.

1. Необходимо реализовать функции для вычисления коэффициента сжимаемости и плотности реального газа с использованием библиотеки NumPy.
2. Рассчитать плотность пропана при атмосферном давлении, значения $T$ принять принадлежащими интервалу $\left[273.15, 298.15\right] \space \mathrm{K}$, $10$ элементов.

Свойства пропана

|Свойство|Значение|Единицы измерения|
|-|-|-|
|Молярная масса|$0.0441$|$\mathrm{кг/моль}$|
|Критическая температура, $T_c$|$370$|$\mathrm{K}$|
|Критическое давление, $P_c$|$4.27$|$\mathrm{МПа}$|

In [53]:
from scipy.constants import R

In [54]:
def calculate_a(
        tc: float,
        pc: float
) -> float:
    return 1 / (9 * (2 ** (1 / 3) - 1)) * R ** 2 * tc ** 2.5 / pc


def calculate_b(
        tc: float,
        pc: float
) -> float:
    return (2 ** (1 / 3) - 1) / 3 * R * tc / pc


def calculate_z(
        tc: float,
        pc: float,
        t: float,
        p: float
) -> float:
    a = calculate_a(tc, pc)
    b = calculate_b(tc, pc)
    _a = a * p / (R ** 2 * t ** 2.5)
    _b = b * p / (R * t)
    p = poly(
        [
            -_a * _b,
            _a - _b ** 2 - _b,
            -1,
            1
        ]
    )
    roots = p.roots()
    roots = roots[np.isreal(roots)].real
    return roots.max()

In [55]:
def calculate_rho(
        m: float,
        t: float,
        p: float,
        z: float
) -> float:
    return m * p / (R * t * z)

In [56]:
m, tc, pc = .0441, 370, 4.27e6
t_array = np.linspace(273.15, 298.15, 10)
p = 101325

In [57]:
z_array = np.zeros_like(t_array)
for i, t in enumerate(t_array):
    z_array[i] = calculate_z(tc, pc, t, p)

0.02166237518572749 0.0027848990335870363
0.021121294265530832 0.002756863325434873
0.02059894704338402 0.0027293864648947285
0.020094507768392857 0.0027024519072448307
0.019607194743765804 0.0026760437544584175
0.019136267575900427 0.002650146723912242
0.01868102461978708 0.0026247461188945854
0.018240800605001363 0.0025998278007931686
0.01781496442795265 0.0025753781628524053
0.017402917097314997 0.0025513841053976154


In [58]:
z_array

array([0.98082407, 0.98135486, 0.98186632, 0.98235933, 0.98283475,
       0.98329337, 0.98373593, 0.98416317, 0.98457574, 0.98497428])

In [59]:
rho_array = np.zeros_like(t_array)
for i, t in enumerate(t_array):
    rho_array[i] = calculate_rho(m, t, p, z_array[i])

In [60]:
rho_array

array([2.00598969, 1.98472123, 1.96391654, 1.94356001, 1.92363674,
       1.90413251, 1.88503372, 1.86632741, 1.84800115, 1.83004307])