# Задание 1

Заполнить матрицу $\mathrm{a}\left(3, 3\right)$ случайными целыми числами от $-5$ до $5$. Вывести значения ее элементов на экран. Найти произведение минимального элемента матрицы на сумму ее положительных элементов. Вывести результат.

In [1]:
import numpy as np

In [2]:
a = np.random.randint(-5, 5, (3, 3))
a

array([[ 2, -1,  4],
       [ 3, -3, -3],
       [-2,  4,  1]])

In [4]:
min_a = a.min()
sum_a = a.sum(where=a>0)
min_a, sum_a, min_a * sum_a

(-3, 14, -42)

# Задание 2

Заполнить матрицу $\mathrm{a}\left(5, 10\right)$ случайными целыми числами от $0$ до $9$. Вывести значения элементов матрицы. Найти столбец матрицы с максимальной суммой элементов и вывести эту сумму на экран.

In [5]:
a = np.random.randint(0, 9, (5, 10))
a

array([[2, 8, 8, 7, 7, 4, 8, 3, 1, 4],
       [5, 1, 7, 3, 8, 5, 5, 3, 5, 8],
       [8, 1, 0, 2, 5, 6, 6, 7, 5, 6],
       [2, 4, 3, 3, 4, 3, 3, 2, 4, 2],
       [2, 8, 7, 3, 8, 3, 6, 4, 7, 1]])

In [7]:
sum_of_cols = a.sum(axis=0)
sum_of_cols, sum_of_cols.max()

(array([19, 22, 25, 18, 32, 21, 28, 19, 22, 21]), 32)

# Задание 3

Найти сумму положительных ($p$) и количество отрицательных ($o$) элементов массива $\mathrm{z}\left(10\right)$, заполненного случайными целыми числами в диапазоне $\left[-7; 5\right]$ и минимальный элемент $\left(b_{min}\right)$ второго столбца матрицы $\mathrm{b\left(5, 5\right)}$, заполненной случайными числами в диапазоне $\left[-10; 20\right]$, и вычислить значения элементов массива $x_i$:

$
	x_i = \dfrac{\sqrt{p}}{o + a \cdot c} + b_{min} \cdot k^2 + z_i
$

где $a = 2.5\mathrm{e-}3; \quad c = 175; \quad k = 8$.

In [8]:
z = np.random.randint(-7, 5, 10)
z

array([ 1, -4, -5, -2,  4,  3, -2, -4,  4,  0])

In [9]:
p = z.sum(where=z>0)
o = z[z<0].shape[0]
p, o

(12, 5)

In [10]:
b = np.random.randint(-10, 20, (5, 5))
b

array([[ 10, -10,   3,  11,  -2],
       [ -2,   3,  18,  -3,  18],
       [ -2,   4,  11,  -3,   6],
       [ 19,  -3,  16,   8,  16],
       [ 16,   6,  -1,   3,   2]])

In [11]:
bmin = b[:, 1].min()
bmin

-10

In [12]:
a, c, k = 2.5e-3, 175, 8

In [13]:
x = p ** .5 / (o + a * c) + bmin * k ** 2 + z
x

array([-638.36292384, -643.36292384, -644.36292384, -641.36292384,
       -635.36292384, -636.36292384, -641.36292384, -643.36292384,
       -635.36292384, -639.36292384])