# 1

In [2]:
import numpy as np

In [3]:
a = np.random.randint(-5, 6, (3, 3))

In [4]:
a

array([[ 0, -2, -5],
       [-5,  5, -3],
       [ 5, -2, -1]])

In [5]:
min_el = a.min()
s_pos = a.sum(where=a > 0)
print(min_el * s_pos)

-50


# 2

In [6]:
a = np.random.randint(0, 10, (5, 10))
a

array([[1, 6, 7, 7, 1, 2, 3, 6, 7, 7],
       [9, 0, 2, 6, 4, 0, 5, 7, 0, 3],
       [8, 0, 2, 8, 7, 7, 6, 4, 7, 9],
       [4, 6, 9, 0, 7, 4, 1, 9, 7, 8],
       [9, 2, 4, 6, 3, 5, 3, 0, 2, 7]])

In [7]:
s_cols = a.sum(axis=0)
s_cols

array([31, 14, 24, 27, 22, 18, 18, 26, 23, 34])

In [9]:
i = s_cols.argmax()
i, s_cols[i]

(9, 34)

# 3

In [11]:
z = np.random.randint(-7, 6, 10)
z

array([ 3, -6,  1,  2,  3,  4, -7, -7,  2, -7])

In [12]:
p = z.sum(where=z > 0)
o = z[z < 0].size
p, o

(15, 4)

In [13]:
b = np.random.randint(-10, 21, (5, 5))
b

array([[-9, 16, -4, 14, 10],
       [-9, 14, -5, 12,  2],
       [-7, -1, 10, -8,  7],
       [-4, -5, 13,  5, 15],
       [10, 17,  6, -2,  6]])

In [14]:
bmin = b[:, 2].min()
bmin

-5

In [15]:
a, c, k = 2.5e-3, 175, 8

In [16]:
x = p ** .5 / (o + a * c) + bmin * k ** 2 + z
x

array([-316.12721502, -325.12721502, -318.12721502, -317.12721502,
       -316.12721502, -315.12721502, -326.12721502, -326.12721502,
       -317.12721502, -326.12721502])